### ISSUE TITLE
Error: Error while connecting: read ETIMEDOUT

### ISSUE THREAD

**Issue by huboshu0819** [tinify/tinify-nodejs#10]
![image](https://user-images.githubusercontent.com/10299842/27577651-17b62ee8-5b54-11e7-9e37-3187c2c73275.png)

It is very slow even though I upload a small image, and always timeout

**Comment by emielvanlankveld** [comment]
Hi, thank you for the report! 

Would you mind sending us your code snippet to support@tinypng.org? If it always times out we would like to investigate whether this is a consistent issue with the library or if there is a problem with the configuration.

**Comment by huboshu0819** [comment]
```
const tinify = require("tinify");
tinify.key = "xxx";
let pro = tinify.fromFile("./upload/num_bg.png").toFile("./upload/num_bg.min.png");
let star = new Date().getTime();
pro.then(function(data){
	let end = new Date().getTime();
	console.log('sucess',end - star);
	console.log(data)
}, function(error){
	console.log(error)
})

```
Today I tried the next, there is no overtime situation, I think it may be a network problem, I will continue to pay attention to this problem and timely feedback

**Comment by Evertrotshuizen** [comment]
Hi huboshu0819,

As you mentioned, it's most likely a network issue. We are currently in the process of upgrading our infrastructure which should help with these sort of issues. We will definitely let our users know once that upgrade has been released.

If you have any further questions please send them to support@tinypng.com and someone will assist you.

**Comment by michielverkoijen** [comment]
I am closing this issue as we finished the infrastructure migration.
