### ISSUE TITLE
I try tinify with the most simple way， but I always got nothing. 

### ISSUE THREAD

**Issue by qreal829475** [tinify/tinify-nodejs#12]
hello, i try it like this:

```
const tinify = require("tinify");
tinify.key = "xxxxxx";

tinify.fromFile("abc.jpg").toFile("optimized.jpg");
```

But, i got nothing.

I don't know why it like this. I think I'll be crazy.

**Comment by qreal829475** [comment]
So sorry. my friend solved this problem just now.

My key has problem. but I got nothing in console. 
Maybe it's a iusse.
Hope your reply.

**Comment by warflower** [comment]
When you're using an incorrect API key you should get an "Credentials are invalid (HTTP 401/Unauthorized)" error though. Copy pasting those three lines to a script, and executing it with node gives me that error.

In any case, I'm happy to hear that you've found out what was causing you to not get a compressed image as result.
