### ISSUE TITLE
Grab a set of files from Folders.

### ISSUE THREAD

**Issue by coldtelling** [tinify/tinify-nodejs#15]
Hi,

Could there be more documentation about using folders, or perhaps just a tip or simple example ?

ex: tinify.fromFile > tinify.fromFolder 

Kindest regards !

**Comment by simonwahlstrom** [comment]
Hi there,

The library currently does not have any specific logic for compressing entire folders. It could be a nice improvement though so I will add it to our improvements lists! 

If you need help on how to get all files from a folder, then perhaps this could be of help:
https://stackoverflow.com/questions/2727167/how-do-you-get-a-list-of-the-names-of-all-files-present-in-a-directory-in-node-j
