### ISSUE TITLE
Cannot assign to 'key' because it is a read-only property. 

### ISSUE THREAD

**Issue by csulit** [tinify/tinify-nodejs#28]

**Comment by eddyh** [comment]
Hi @csulit,

Could you please share a minimal code example that raises this error? Also could you share your version of NodeJS?

Thanks!

**Comment by csulit** [comment]
> Hi @csulit,
> 
> Could you please share a minimal code example that raises this error? Also could you share your version of NodeJS?
> 
> Thanks!

Problem solved.

it's not working if you import the library like this "import * as libname from 'libname';

**Comment by eddyh** [comment]
Good to hear you found the issue!
