### ISSUE TITLE
Resize function not working fine

### ISSUE THREAD

**Issue by lechidung** [tinify/tinify-nodejs#35]
I resized image from size 1600x1043 px via resize function of tinify but after resize the size size is 1600x1043 it's not resize image!

My source code:
```
const resized = tinify.fromFile(fileSource);
resized.resize({
  method: 'scale',
  width: 600
});
resized.toFile(fileSourceResize);
```

**Comment by ddmicu** [comment]
Could you please send the original image to [support@tinypng.com](mailto:support@tinypng.com) so we can have a look?
