### ISSUE TITLE
are there any docs on the convert functionality?

### ISSUE THREAD

**Issue by johnnyreilly** [tinify/tinify-nodejs#40]
I can see the ability was added to convert images. Docwise I can't see anything, but I can see this code in the tests:

```
      .convert({type:["image/webp", "image/jpg"]})
```

https://github.com/tinify/tinify-nodejs/pull/39/files#diff-887779faeffe0d98f0035c4daf646e3c83f535e4ae53943482026ea8b19f923bR91

Does this mean convert to `webp` from `jpeg`?

**Comment by ddmicu** [comment]
We are planning to update the documentation on our website asap but we are still in the process of releasing the new functionality in all the other Tinify API clients.

To answer your question, the example mentioned by you returns the smallest version of the image between webp and jpeg. 

The following options are available as a type:
- One image type, specified as a string "image/webp".
- Multiple image types, specified as an array ["image/webp","image/png"]. The smallest of the provided image types will be returned.
- The wildcard "*/*" returns the smallest of Tinify's supported image types, currently JPEG, PNG and WebP.

.transform: 
The transform object specifies the stylistic transformations that will be applied to your image. Include a background property to fill a transparent image's background. The following options are available to specify a background color:
- A hex value. Custom background color using the color's hex value: "#D02670".
- "white" or "black". Only the colors white and black are supported as strings.
You must specify a background color if you wish to convert an image with a transparent background to an image type which does not support transparency (like JPEG).

Hope this helps!

**Comment by johnnyreilly** [comment]
It does!

**Comment by johnnyreilly** [comment]
Question: how do you know which type of image has been generated?

**Comment by ddmicu** [comment]
We have some helper methods that you can use:  content type (.mediaType()) or directly the extension as in the following example: 

const source = tinify.fromFile("unoptimized.jpg");
const converted = source.convert({type:["image/webp","image/png"]});
const extension = converted.**result().extension()**;
converted.toFile("converted-image." + extension);

**Comment by johnnyreilly** [comment]
Nice! I was looking at the types you're exposing on `convert` and I can see it's just an object:

```ts
  convert(options: object): Source {
```

https://github.com/tinify/tinify-nodejs/blob/95e52888045dd42d67b79f4175cf6ab33f284710/src/tinify/Source.ts#L88

Would you welcome a PR which made the type more explicit given the details you've provided in this chat?

**Comment by johnnyreilly** [comment]
Have raised a speculative PR here: https://github.com/tinify/tinify-nodejs/pull/41

**Comment by ddmicu** [comment]
Thank you for the PR. We are planning to do the same for all our functions in the near future and we will review your changes in detail when we will get started.

One thing I've noted is the wildcard in my original comment was / but in reality is \*/\* . I did not realise that in these comments I need to escape some characters. Sorry for the confusion!

**Comment by johnnyreilly** [comment]
> One thing I've noted is the wildcard in my original comment was / but in reality is */* . I did not realise that in these comments I need to escape some characters. Sorry for the confusion!

Haha! No worries - I've updated the PR to reflect
