### ISSUE TITLE
TypeScript Import error

### ISSUE THREAD

**Issue by sdack-cloud** [tinify/tinify-nodejs#44]
```
let tinify1 = require('tinify')
OR
import tinify from 'tinify'


tinify.key = "123";
```

ERROR

Reason: TypeError: fs.readFileSync is not a function

nodejs v15.14.0
npm 7.7.6
"tinify": "^1.7.1",
"vue": "^2.6.11",
"typescript": "~4.1.5",

**Comment by sdack-cloud** [comment]
![image](https://github.com/tinify/tinify-nodejs/assets/49465225/12433c2d-3111-452d-9fe8-4bd995a75e00)

**Comment by sdack-cloud** [comment]
![image](https://github.com/tinify/tinify-nodejs/assets/49465225/263ec17d-b920-48c7-b562-0425bbbf80d7)

**Comment by sdack-cloud** [comment]
Using uni app
```
vue create -p dcloudio/uni-preset-vue uni-type-demo
```

**Comment by rkoopmans** [comment]
Hey sdack-cloud,

The tinify-nodejs client is not build or meant to be run in a frontend app. 

In case you use a frontend framework with API views, use the tinify client only in the server code.

The problem with running Tinify in frontend code, is that your API key will be leaked in the user browser., therefore using the API directly in a browser context is not made possible.
